version: "3.8"

services:
  tana-api:
    build: .
    image: jliotorresmoreno/tana:latest
    container_name: tana-api-container
    ports:
      - "8000:8000"
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
